'''
Created on 5 Jul 2013

@author: Mark.rowlands
'''
from root.nested.tests.base_aim_regression_test import BaseAimRegressionTest

class AimAddUserGroupPageFunctionsTest(BaseAimRegressionTest):
    
    name = "users new"
    
    def test_cannot_create_user_group_without_name(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self.assertEqual(self._page.get_text_of_page_header(), "User Groups > Add User Group")
        self.assertFalse(self._page.is_ajax_error_message_displayed_for_user_group())
        self._page.click_save_ignore_warnings()
        self.assertTrue(self._page.is_ajax_error_message_displayed_for_user_group())
    
    def test_can_create_user_group_with_name_but_no_members_or_permissions(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_name(users[-1]), self.name)
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()
        
    def test_can_create_user_group_with_allow_exclusive_no(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.select_user_group_exclusive_no()
        self._page.add_default_members_to_user_group()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_connection_image_src(users[-1]), self._baseurl + "/admin/images/silk_icons/cross.png")
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()

    def test_can_create_user_group_with_allow_exclusive_global(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.select_user_group_exclusive_global()
        self._page.add_default_members_to_user_group()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_connection_image_src(users[-1]), self._baseurl + "/admin/images/silk_icons/inherit.png")
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()

    def test_can_create_user_group_with_allow_exclusive_yes(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.select_user_group_exclusive_yes()
        self._page.add_default_members_to_user_group()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_connection_image_src(users[-1]), self._baseurl + "/admin/images/silk_icons/tick.png")
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()
    
    def test_can_create_user_group_with_user(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.add_default_members_to_user_group()
        self._page.add_member_to_user_group_via_user_config_page()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self.assertTrue(self._page.check_member_in_user_group_via_user_config_page())
        self._page.driver.back()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()
    
    def test_can_create_user_group_with_channel_permission(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.add_default_members_to_user_group()
        self._page.add_channel_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self.assertTrue(self._page.check_channel_permission_for_user_group_via_user_group_config_page())
        self._page.driver.back()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()

    def test_can_create_user_group_with_channel_group_permission(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.add_default_members_to_user_group()
        self._page.add_channel_group_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self.assertTrue(self._page.check_channel_group_permission_for_user_group_via_user_group_config_page())
        self._page.driver.back()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()

    def test_can_create_user_group_with_receiver_permission(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.show_receiver_permissions()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.remove_all_receivers_from_user_group()
        self._page.add_receiver_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.show_receiver_permissions()
        self.assertTrue(self._page.check_receiver_permission_for_user_group_via_user_group_config_page())
        self._page.driver.back()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()

    def test_can_create_user_group_with_receiver_group_permission(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_add_user_group_page()
        self._page.show_receiver_permissions()
        self._page.set_user_group_name_via_config_page(self.name)
        self._page.remove_all_receivers_from_user_group()
        self._page.add_receiver_group_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        self._page.check_for_error_message("configure_user_group_ajax_message")
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.show_receiver_permissions()
        self.assertTrue(self._page.check_receiver_group_in_user_group_via_user_group_config_page())
        self._page.driver.back()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_delete(users[-1])
        self._page.click_lightbox_delete_button()