'''
Created on 4 Jul 2013

@author: Mark.rowlands
'''
from root.nested.tests.base_aim_regression_test import BaseAimRegressionTest

class AimUserGroupConfigPageFunctionsTest(BaseAimRegressionTest):
    
    def test_can_change_name(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        name = self._page.get_user_group_name(users[-1])
        self._page.click_user_group_config(users[-1])
        self._page.set_user_group_name_via_config_page(name + " edit")
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_name(users[-1]), name + " edit")
        self._page.click_user_group_config(users[-1])
        self._page.set_user_group_name_via_config_page(name)
        self._page.click_save()
    
    def test_can_change_allowed_exclusive_connection_to_no(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.select_user_group_exclusive_no()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_connection_image_src(users[-1]), self._baseurl + "/admin/images/silk_icons/cross.png")
        self._page.click_user_group_config(users[-1])
        self._page.select_user_group_exclusive_global()
        self._page.click_save()

    def test_can_change_allowed_exclusive_connection_to_global(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.select_user_group_exclusive_no()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.select_user_group_exclusive_global()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_connection_image_src(users[-1]), self._baseurl + "/admin/images/silk_icons/inherit.png")

    def test_can_change_allowed_exclusive_connection_to_yes(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.select_user_group_exclusive_yes()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self.assertEqual(self._page.get_user_group_connection_image_src(users[-1]), self._baseurl + "/admin/images/silk_icons/tick.png")
        self._page.click_user_group_config(users[-1])
        self._page.select_user_group_exclusive_global()
        self._page.click_save()
    
    def test_can_change_member_users_of_group(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.add_member_to_user_group_via_user_config_page()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self.assertTrue(self._page.check_member_in_user_group_via_user_config_page())
        fixed_users = ["admin", "anon", "api_anon"]
        all_users = self._page.get_all_members_of_user_group()
        remove_users = list(set(all_users) - set(fixed_users))
        for user in remove_users:
            self._page.remove_member_from_user_group_permission(user)
        self._page.click_save()
    
    def test_can_change_channel_permissions_of_user_group(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.remove_all_channels_from_user_group()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.add_channel_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self.assertTrue(self._page.check_channel_permission_for_user_group_via_user_group_config_page())
        self._page.add_all_channel_permissions_to_user_group_via_user_group_config_page()
        self._page.click_save()
    
    def test_can_change_channel_group_permissions_of_user_group(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.remove_all_channel_groups_from_user_group()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.add_channel_group_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self.assertTrue(self._page.check_channel_group_permission_for_user_group_via_user_group_config_page())
        self._page.add_all_channel_group_permissions_to_user_group_via_user_group_config_page()
        self._page.click_save()
    
    def test_can_change_receiver_permissions_of_user_group(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.show_receiver_permissions()
        self._page.remove_all_receivers_from_user_group()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.show_receiver_permissions()
        self._page.add_receiver_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.show_receiver_permissions()
        self.assertTrue(self._page.check_receiver_permission_for_user_group_via_user_group_config_page())
        self._page.add_all_receiver_permissions_to_user_group_via_user_group_config_page()
        self._page.click_save()
    
    def test_can_change_receiver_group_permissions_of_user_group(self):
        self._page.open_AIM_homepage_on_base_url()
        self._page.login_as("admin", "password", False)
        self._page.open_users_tab()
        self._page.open_view_user_groups_page()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.show_receiver_permissions()
        self._page.add_receiver_group_permission_to_user_group_via_user_group_config_page()
        self._page.click_save()
        users = self._page.get_list_of_user_groups()
        self._page.click_user_group_config(users[-1])
        self._page.show_receiver_permissions()
        self.assertTrue(self._page.check_receiver_group_in_user_group_via_user_group_config_page())
        self._page.remove_all_receiver_group_permissions_via_user_group_config_page()
        self._page.click_save()